### ISSUE TITLE
Execute a custom ffmpeg command

### ISSUE THREAD

**Issue by brainunknown** [sbis04/video_trimmer#138]
First of all congratulations for this great package :) I hope some day I will be able to do something like this.

**Since this package has the ffmpeg, can we execute a custom ffmpeg command?**

 **For instance, what I need is to capture a single image of a video.** I know, here was recommended the package video_thumbnail, but I don't want to have too many packages installed.

And since video_trimmer already has ffmpeg we could use it instead.

I tried:

        `.saveTrimmedVideo(startValue: _startValue, endValue: _endValue, ffmpegCommand: 'ffmpeg -ss 01:23:45 -i input -vframes 1 -q:v 2', customVideoFormat: '.jpg')
`

**Comment by sbis04** [comment]
Yes, you can use a custom FFmpeg command (you can check out the correct way to capture an image from the Docs [here](https://ffmpeg.org/ffmpeg.html)) but this is not recommended because in order to use the `saveTrimmedVideo()` method you should be showing the `TrimEditor` UI which is suited for only trimming videos.
