### ISSUE TITLE
Trimmed video first seconds sometimes stuck

### ISSUE THREAD

**Issue by omercn18** [sbis04/video_trimmer#22]
Hi!
First of all, I love this new package,
While I was using it, I realized that sometimes the video is stuck in the first few seconds after it was trimmed (but the audio is still playing).
I think that it is because of the FFmpeg command, but I'm not sure and couldn't find the exact reason.

**Comment by omercn18** [comment]
@sbis04 Hi,
Did you find anything?

**Comment by braysonjohn148** [comment]
was using FFmpeg before this. It was also stucking. Anybody finds a better solution for this

**Comment by braysonjohn148** [comment]
Any new...

**Comment by sbis04** [comment]
Hi @omercn18 @braysonjohn148, I took a look at the issue and found out that giving the time in the formats like, `HH:MM:SS.xx` or `SS.xx` is causing this issue.

Upon further investigation, I found out that removing these decimal places present after the seconds is resolving this issue.

So, I have updated this in the version 0.2.4

Let me know if it fixes the issue.

**Comment by omercn18** [comment]
Well, it seems like 0.2.4 is not public yet.
I'll update when it will be.

**Comment by sbis04** [comment]
Now the v0.2.4 is public, do give it a try @omercn18

**Comment by vercorro** [comment]
Changed the command like you did in v0.2.4, the first frames still freezing :/ . Please help

**Comment by omercn18** [comment]
@sbis04 Well same as what @vercorro said, first frames are freezing..

**Comment by sbis04** [comment]
Hi @vercorro @omercn18 Can you please cross-check that you are using the version **0.2.4**?

In your `pubspec.yaml` file import it like: 
```yaml
video_trimmer: 0.2.4
```
That is, without the carat sign.

Also, go to `pubspec.lock` file and make sure that the version is correct.

Just let me know about this?

**Comment by vercorro** [comment]
> Hi @vercorro @omercn18 Can you please cross-check that you are using the version **0.2.4**?
> 
> In your `pubspec.yaml` file import it like:
> 
> ```yaml
> video_trimmer: 0.2.4
> ```
> 
> That is, without the carat sign.
> 
> Also, go to `pubspec.lock` file and make sure that the version is correct.
> 
> Just let me know about this?

Hi sbis04, thank you for your reply and your contribution into flutter community.  I actually imported your whole library files into my projet so I dont use it as a dependency. It works well besides those first frames. I looked into your update for the 0.2.4 and the only modification is the command line (correct me if I'm wrong). So I replaced the line exactly like you did and still have freezing frames.

**Comment by omercn18** [comment]
> Hi @vercorro @omercn18 Can you please cross-check that you are using the version **0.2.4**?
> 
> In your `pubspec.yaml` file import it like:
> 
> ```yaml
> video_trimmer: 0.2.4
> ```
> 
> That is, without the carat sign.
> 
> Also, go to `pubspec.lock` file and make sure that the version is correct.
> 
> Just let me know about this?

Yes, version is 0.2.4

**Comment by leochiu-work** [comment]
I also faced this issue in version 0.2.4, is there any update?

**Comment by sbis04** [comment]
The issue with the starting and ending video frames freezing still persists. Changing the FFmpeg trim video start & end position to **seconds** does not fix the issue, so I will be reverting it to **milliseconds** as before in the `v0.2.5`.

As per [this](https://video.stackexchange.com/a/16640) thread, the freezing issue occurs due to the video not being cut from an `I-frame`. But, I couldn’t yet figure out a proper method for finding an `I-frame` from a video.

This can be fixed by re-encoding the video as per PR #34, but this will take significantly more time.

**Comment by tinnit1** [comment]
This problem is solved by changing this line -i "$ _videoPath" -ss $ startPoint -t $ {endPoint - startPoint} by this -i "$ _videoPath" -ss $ startPoint -to $ {endPoint - startPoint} and add -copyts to the line -c copy

**Comment by sbis04** [comment]
@tinnit1 I tried with the following changes, but still the video freezes for some time at the starting point:

```dart
String _trimLengthCommand = '-i "$_videoPath" -ss $startPoint -to ${endPoint - startPoint}';
```

```dart
_command = '$_trimLengthCommand -c copy -copyts ';
```

**Comment by tinnit1** [comment]
Try this, in this order. if not work maybe it can be an instance ffmpeg that it have conflict.

`String _trimLengthCommand = '-ss $startPoint -i "$_videoPath" -to ${endPoint - startPoint}' -c copy -copyts $OutputPath;`

**Comment by sbis04** [comment]
Using this is causing an unusual timeline, i.e. the start time doesn't begin from 0. It starts from the start time in which position the video is cut from the original one. Check the screen recording:

![trimming_issue](https://user-images.githubusercontent.com/43280874/88376470-1a2da980-cdbb-11ea-8ef3-12f207ff5216.gif)

**Comment by sbis04** [comment]
A temporary fix has been deployed in **v0.2.6**: Added a new property to `saveTrimmedVideo()` method called `applyVideoEncoding` which will let you specify whether to re-encode the trimmed video.

**NOTE:** Applying this will take a significantly greater amount of time to process the output video.

Refer to: 30f6015afcc33dbd2586d07718f9c8f0a33ab5ef

**Comment by leochiu-work** [comment]
Thanks for the temporary fix in v0.2.6.
After setting applyVideoEncoding = true, the video quality becomes bad.
Is it expected?

**Comment by foxy17** [comment]
> @sbis04 Thanks for the temporary fix in v0.2.6.
> After setting applyVideoEncoding = true, the video quality becomes bad.
> Is it expected?

it becomes way worse than normal quality and the drop is quite noticeable when the original video is of 720p resolution

**Comment by masfour7** [comment]
No solution yet?

**Comment by masfour7** [comment]
did anyone find any solution to this?

**Comment by omercn18** [comment]
@sbis04 Hi, do you see any good fix for this issue coming soon?
applyVideoEncoding takes a lot of time and destroys the video.

**Comment by courtneypresto** [comment]
Hey @omercn18 and @sbis04 I found a really easy fix. 
Right how you have this: 
`String _trimLengthCommand = '-i "$_videoPath" -ss $startPoint -t ${endPoint - startPoint}';`

And you need to change it to this: `String _trimLengthCommand =
        ' -ss $startPoint -i "$_videoPath" -t ${endPoint - startPoint}';`

**Comment by kasyrm** [comment]
Awesome, it works!
Thanks 👍

**Comment by ArjanAswal** [comment]
@courtneypresto Thanks a lot for finding this amazing solution! I created a [PR](https://github.com/sbis04/video_trimmer/pull/59#issue-507730609) with this change. The only problem being that video duration gets shortened by exactly 600ms. 

So I changed the command to 
`    String _trimLengthCommand = ' -ss $startPoint -i "$_videoPath" -t ${endPoint - startPoint + durationCorrection}';
`

@sbis04  There is also another problem, however, this one existed all the time - When starting time is any non zero value, the video still gets stuck, most likely because it is waiting for the nearest keyframe, we have yet to find the solution for this problem. WhatsApp tackles this by starting and ending the trimmed video with the nearest keyframe timestamp. That's why the trimmed video in WhatsApp starts and ends with different timestamps than we intended to. I think we can too implement this in the plugin.

**Comment by sbis04** [comment]
@ArjanAswal @kasyrm @courtneypresto This solution had been presented long before by @tinnit1, I had tested this at that time, but this results in a much worse scenario because if the video doesn't start from the initial starting point then the timeline gets distorted, and sometimes that weird trimmed video isn't even playable. Refer: https://github.com/sbis04/video_trimmer/issues/22#issuecomment-663434391

I would suggest avoiding this solution at this point.

And, yes @ArjanAswal this problem can be solved if the video can be trimmed from a keyframe. But still, I haven't found any efficient approach to get that, refer: https://github.com/sbis04/video_trimmer/issues/22#issuecomment-660572809

I would appreciate a **PR** if someone can retrieve the keyframes of the video and use them for trimming, rather than trimming from any random point.

**Comment by ArjanAswal** [comment]
@sbis04 Retrieving keyframes of the video can be implemented by using the `ffprobe -show_frames` command. It can take a bit of time to complete although I've never tried it.  That's one way. I'll look into it.

Also, courtneypresto's solution still stands good if initial position of video is zero, atleast we can implement it in that special case.  We can have best of both worlds until we find the optimal solution for this issue.

```  
     String _trimLengthCommand = '-i "$_videoPath" -ss $startPoint -t ${endPoint - startPoint}';
     
     if(startValue == 0){
       _trimLengthCommand = ' -ss $startPoint -i "$_videoPath" -t ${endPoint - startPoint + durationCorrection}';
     }
```

**Comment by courtneypresto** [comment]
Hmm okay I haven't actually tried it yet but I just found [this solution](https://github.com/mifi/lossless-cut/pull/13#issuecomment-419737980) which distinguishes a normal cut (nc) with a keyframe cut (kc)... and doesn't need the cut to actually start at 00:00. 

Someone provided an example [here](https://github.com/mifi/lossless-cut/pull/13#issuecomment-447127223).

Seems promising! @ArjanAswal @sbis04

**Comment by ArjanAswal** [comment]
@courtneypresto Adding `-avoid_negative_ts make_zero` rectifies the problem that @sbis04 mentioned [here](https://github.com/sbis04/video_trimmer/issues/22#issuecomment-663434391).

I think we have now solved the issue. The only problem being that the starting point of the trimmed video picks the keyframe that is earlier instead of the later one.
For example, we want to trim a video from 10s to 50s timestamp. Let's say the 2 keyframes nearest to the 10s timestamp are 9s and 11s. Now instead of picking the 11s, it picks the 9s timestamp which makes the video 41 seconds long instead of 39.

That is a trade-off we can make, for now, at least it is better than the video getting frozen for 1-2 seconds in the beginning.
Now, it is up to @sbis04 to make the final decision.
