### ISSUE TITLE
/data/user/0/MyProject/files/ffmpeg": error=13, Permission denied

### ISSUE THREAD

**Issue by yoonjiyong** [sbis04/video_trimmer#71]
Hi,

I changed targetSdk 29 for upload google playstore. ( google targetSdk policy )

Now I got this error 

when I click (button),  phone die immediately
these code 
`await _trimmer
    .saveTrimmedVideo(startValue: _startValue, endValue: _endValue)
    .then((value) {
  setState(() {
    _value = value;
  });
})`

and error message like this 
E/FFmpeg  ( 9618): java.io.IOException: Cannot run program "/data/user/0/myProject/files/ffmpeg": error=13, Permission denied

is there a way to solve this problem? 
( targetSdk 28 was no problem )

**Comment by sbis04** [comment]
I think this issue is related to [[Android Q Beta] Apps can no longer execute binaries in their home directory](https://issuetracker.google.com/issues/128554619). 

Also, refer to this StackOverflow thread [here](https://stackoverflow.com/questions/60370424/permission-is-denied-using-android-q-ffmpeg-error-13-permission-denied).

And, I think if you follow up in this thread you would get a better solution: https://github.com/tanersener/flutter-ffmpeg/issues/232

**Comment by tanersener** [comment]
@sbis04 `flutter-ffmpeg` does not provide or use an `ffmpeg` binary. Therefore, `flutter-ffmpeg` won't provide a fix for it.

**Comment by sbis04** [comment]
Okay @tanersener, in this package the `flutter-ffmpeg` library is directly used, so `ffmpeg` binary shouldn't have any involvement here @yoonjiyong 

Closing this issue.
